### ISSUE TITLE
Portal To The Last Millenium doesn't work

### ISSUE THREAD

**Issue by thebrightspark** [8BrickDMG/Affinity-Infinity#4]
Right clicking on the portal does nothing. Known issue for Extra Utilities, and other people also say that the Portal To The Deep Dark doesn't work either.

https://github.com/rwtema/extrautilities/issues/553

According to someone in that bug report:
"This is fixed by installing Player API as -instructed- on the Galacticraft compatibility wiki page. Links: http://wiki.micdoodle8.com/wiki/Compatibility#Any_other_mod_with_.27Fake_Player.27_detection http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996"

**Comment by 8BrickDMG** [comment]
Tested and fixed by installing the PlayerAPI.
