### ISSUE TITLE
IndustrialCraft 2 Infinite Power

### ISSUE THREAD

**Issue by 8BrickDMG** [8BrickDMG/Affinity-Infinity#5]
Pack version: 3.0
Mod: IndustrialCraft 2
Bug: Hooking up a universal cable from Mekanism to any IC2 storage, causes whatever generator hooked up to the cable to only ever take energy out once and infinitely forever.
Can it be replicated: Yes

**Comment by thebrightspark** [comment]
A more accurate description of what's happening:

IC2 storage blocks do not remove any power from universal cable, therefore if there is power in the cable, the energy storage will infinitely pull energy from the cable.
