### ISSUE TITLE
Can't make Railcraft Wooden Ties

### ISSUE THREAD

**Issue by thebrightspark** [8BrickDMG/Affinity-Infinity#8]
Pack version: AI4 v1.2
Mod: Railcraft / Immersive Engineering
Bug: Can't make Railcraft Wooden Ties. Their only recipe is using the Railcraft creosote oil, however both that and the Immersive Engineering creosote are ore dictionaried to the same liquid and the IE one is the default you retrieve from tanks and coke ovens. There is no recipe for wooden ties using the IE creosote.
Can it be replicated: Yes

**Comment by 8BrickDMG** [comment]
Until this has been resolved, I'm going to add in a recipe to switch between the two versions.

Original thread found below.
https://github.com/BluSunrize/ImmersiveEngineering/issues/101
